export const dummyDataCols = ["id", "name", "gender", "jobs"];
export const dummyDataChart = [
    {
        id: 1,
        name: "Adelheid Attril",
        gender: "Female",
        jobs: "Librarian",
    },
    {
        id: 2,
        name: "Emmalyn Korpal",
        gender: "Female",
        jobs: "Assistant Professor",
    },
    {
        id: 3,
        name: "Sheilah Macknish",
        gender: "Female",
        jobs: "Physical Therapy Assistant",
    },
    {
        id: 4,
        name: "Merci Sargeaunt",
        gender: "Female",
        jobs: "Engineer I",
    },
    {
        id: 5,
        name: "Cyril McCutcheon",
        gender: "Male",
        jobs: "Analog Circuit Design manager",
    },
    {
        id: 6,
        name: "Danyelle Hellsdon",
        gender: "Female",
        jobs: "Cost Accountant",
    },
    {
        id: 7,
        name: "Monti Sitford",
        gender: "Male",
        jobs: "Structural Analysis Engineer",
    },
    {
        id: 8,
        name: "Vladimir Esslemont",
        gender: "Male",
        jobs: "Human Resources Manager",
    },
    {
        id: 9,
        name: "Thayne Rosario",
        gender: "Male",
        jobs: null,
    },
    {
        id: 10,
        name: "Brett Corthes",
        gender: "Male",
        jobs: "Help Desk Operator",
    },
    {
        id: 11,
        name: "Lynsey Donaldson",
        gender: "Female",
        jobs: "Web Designer II",
    },
    {
        id: 12,
        name: "Cori McDonagh",
        gender: "Male",
        jobs: "Data Coordiator",
    },
    {
        id: 13,
        name: "Bartlett Ganders",
        gender: "Male",
        jobs: "Recruiter",
    },
    {
        id: 14,
        name: "Curcio Jantet",
        gender: "Male",
        jobs: "Financial Advisor",
    },
    {
        id: 15,
        name: "Evonne Salan",
        gender: "Female",
        jobs: "Chemical Engineer",
    },
    {
        id: 16,
        name: "Gib Pickworth",
        gender: "Male",
        jobs: "Quality Control Specialist",
    },
    {
        id: 17,
        name: "Beckie de Juares",
        gender: "Female",
        jobs: "Staff Scientist",
    },
    {
        id: 18,
        name: "Sindee Durdy",
        gender: "Female",
        jobs: "Marketing Manager",
    },
    {
        id: 19,
        name: "Judy Bagge",
        gender: "Female",
        jobs: "Software Consultant",
    },
    {
        id: 20,
        name: "Friedrick Dendon",
        gender: "Male",
        jobs: "Legal Assistant",
    },
    {
        id: 21,
        name: "Averell Hafford",
        gender: "Male",
        jobs: "Compensation Analyst",
    },
    {
        id: 22,
        name: "Paulo Rudolf",
        gender: "Male",
        jobs: "Chemical Engineer",
    },
    {
        id: 23,
        name: "Rogerio Vittori",
        gender: "Male",
        jobs: "Technical Writer",
    },
    {
        id: 24,
        name: "Jule Tregona",
        gender: "Male",
        jobs: "Structural Engineer",
    },
    {
        id: 25,
        name: "Fan Older",
        gender: "Female",
        jobs: "Tax Accountant",
    },
    {
        id: 26,
        name: "Nada Bengall",
        gender: "Female",
        jobs: "Editor",
    },
    {
        id: 27,
        name: "Olga Murra",
        gender: "Female",
        jobs: "Geological Engineer",
    },
    {
        id: 28,
        name: "Lolita Tranckle",
        gender: "Female",
        jobs: "Community Outreach Specialist",
    },
    {
        id: 29,
        name: "Colette Tressler",
        gender: "Female",
        jobs: "Biostatistician I",
    },
    {
        id: 30,
        name: "Lianne Darridon",
        gender: "Female",
        jobs: "Geologist II",
    },
    {
        id: 31,
        name: "Thorndike Sandyford",
        gender: "Male",
        jobs: "Senior Quality Engineer",
    },
    {
        id: 32,
        name: "Kassandra Swatman",
        gender: "Female",
        jobs: "Software Engineer IV",
    },
    {
        id: 33,
        name: "Sibyl Nattriss",
        gender: "Female",
        jobs: "Professor",
    },
    {
        id: 34,
        name: "Mitchell Spurrior",
        gender: "Male",
        jobs: "Sales Associate",
    },
    {
        id: 35,
        name: "Mireielle Bertin",
        gender: "Female",
        jobs: "Cost Accountant",
    },
    {
        id: 36,
        name: "Donetta Swinfen",
        gender: "Female",
        jobs: "Social Worker",
    },
    {
        id: 37,
        name: "Loleta Dowall",
        gender: "Female",
        jobs: "Systems Administrator IV",
    },
    {
        id: 38,
        name: "Sherlock Brandsen",
        gender: "Male",
        jobs: "Data Coordiator",
    },
    {
        id: 39,
        name: "Blinnie Rizzardi",
        gender: "Female",
        jobs: "Staff Accountant I",
    },
    {
        id: 40,
        name: "Lambert Grandisson",
        gender: "Male",
        jobs: "Safety Technician I",
    },
    {
        id: 41,
        name: "Othilia Harmond",
        gender: "Female",
        jobs: "Automation Specialist III",
    },
    {
        id: 42,
        name: "Felipe Knappe",
        gender: "Male",
        jobs: "Cost Accountant",
    },
    {
        id: 43,
        name: "Leslie Boam",
        gender: "Male",
        jobs: "Teacher",
    },
    {
        id: 44,
        name: "Cyrus Coners",
        gender: "Male",
        jobs: "Assistant Media Planner",
    },
    {
        id: 45,
        name: "Eleanor Witz",
        gender: "Female",
        jobs: "Electrical Engineer",
    },
    {
        id: 46,
        name: "Farrand Wheble",
        gender: "Female",
        jobs: "Software Test Engineer I",
    },
    {
        id: 47,
        name: "Artus Knapp",
        gender: "Male",
        jobs: "Physical Therapy Assistant",
    },
    {
        id: 48,
        name: "Jeremias Petrakov",
        gender: "Male",
        jobs: "Structural Analysis Engineer",
    },
    {
        id: 49,
        name: "Kienan Dulton",
        gender: "Male",
        jobs: "Paralegal",
    },
    {
        id: 50,
        name: "Seth Sibbet",
        gender: "Male",
        jobs: null,
    },
    {
        id: 51,
        name: "Sherwin Tittershill",
        gender: "Male",
        jobs: "Registered Nurse",
    },
    {
        id: 52,
        name: "Cherry Chatelot",
        gender: "Female",
        jobs: "Marketing Manager",
    },
    {
        id: 53,
        name: "Dorise Cartmail",
        gender: "Female",
        jobs: null,
    },
    {
        id: 54,
        name: "Iosep Wastell",
        gender: "Male",
        jobs: "Marketing Assistant",
    },
    {
        id: 55,
        name: "Merline Rosendale",
        gender: "Female",
        jobs: "Programmer Analyst I",
    },
    {
        id: 56,
        name: "Robb Klimes",
        gender: "Male",
        jobs: "Software Engineer I",
    },
    {
        id: 57,
        name: "Erica Harvison",
        gender: "Female",
        jobs: "Developer III",
    },
    {
        id: 58,
        name: "Wilhelm Antoszczyk",
        gender: "Male",
        jobs: "General Manager",
    },
    {
        id: 59,
        name: "Seth Scatchar",
        gender: "Male",
        jobs: "Database Administrator II",
    },
    {
        id: 60,
        name: "Kipp Jakov",
        gender: "Female",
        jobs: "Civil Engineer",
    },
    {
        id: 61,
        name: "Tessi Down",
        gender: "Female",
        jobs: "Environmental Tech",
    },
    {
        id: 62,
        name: "Augustine Hallard",
        gender: "Male",
        jobs: "Nurse",
    },
    {
        id: 63,
        name: "Fidelity Bonds",
        gender: "Female",
        jobs: "Automation Specialist III",
    },
    {
        id: 64,
        name: "Conrade Slate",
        gender: "Male",
        jobs: "Senior Quality Engineer",
    },
    {
        id: 65,
        name: "Raffaello Hargerie",
        gender: "Male",
        jobs: "VP Sales",
    },
    {
        id: 66,
        name: "Lilllie Regina",
        gender: "Female",
        jobs: "Recruiter",
    },
    {
        id: 67,
        name: "Domini McCartney",
        gender: "Female",
        jobs: "Programmer I",
    },
    {
        id: 68,
        name: "Marlowe McKibbin",
        gender: "Male",
        jobs: "Administrative Officer",
    },
    {
        id: 69,
        name: "Darbee Woodard",
        gender: "Male",
        jobs: null,
    },
    {
        id: 70,
        name: "Faustina Gilleson",
        gender: "Female",
        jobs: "Design Engineer",
    },
    {
        id: 71,
        name: "Munroe Keaton",
        gender: "Male",
        jobs: "Product Engineer",
    },
    {
        id: 72,
        name: "Shelagh Maillard",
        gender: "Female",
        jobs: "Programmer Analyst IV",
    },
    {
        id: 73,
        name: "Roscoe Fadian",
        gender: "Male",
        jobs: "Help Desk Technician",
    },
    {
        id: 74,
        name: "Anabella Puttock",
        gender: "Female",
        jobs: "Information Systems Manager",
    },
    {
        id: 75,
        name: "Ricky Goodsall",
        gender: "Male",
        jobs: "Civil Engineer",
    },
    {
        id: 76,
        name: "Stevy Smalles",
        gender: "Male",
        jobs: "Recruiting Manager",
    },
    {
        id: 77,
        name: "Magdalene Hodgon",
        gender: "Female",
        jobs: "Speech Pathologist",
    },
    {
        id: 78,
        name: "Davey Aberdeen",
        gender: "Male",
        jobs: "Junior Executive",
    },
    {
        id: 79,
        name: "Mil Zupo",
        gender: "Female",
        jobs: "Help Desk Operator",
    },
    {
        id: 80,
        name: "Prescott Waddie",
        gender: "Male",
        jobs: "Structural Analysis Engineer",
    },
    {
        id: 81,
        name: "Godiva Poynter",
        gender: "Female",
        jobs: "Administrative Assistant I",
    },
    {
        id: 82,
        name: "Davy Beaten",
        gender: "Male",
        jobs: "Safety Technician II",
    },
    {
        id: 83,
        name: "Dino Willoughey",
        gender: "Male",
        jobs: "Environmental Specialist",
    },
    {
        id: 84,
        name: "Lanie Rihosek",
        gender: "Female",
        jobs: "Environmental Specialist",
    },
    {
        id: 85,
        name: "Jane Scholtis",
        gender: "Female",
        jobs: "Research Nurse",
    },
    {
        id: 86,
        name: "Ora Mandrey",
        gender: "Female",
        jobs: "Financial Advisor",
    },
    {
        id: 87,
        name: "Sonny Keates",
        gender: "Female",
        jobs: "Structural Analysis Engineer",
    },
    {
        id: 88,
        name: "Sadie Passby",
        gender: "Female",
        jobs: "Web Designer IV",
    },
    {
        id: 89,
        name: "Basia Peascod",
        gender: "Female",
        jobs: "Occupational Therapist",
    },
    {
        id: 90,
        name: "Beatrice Teresia",
        gender: "Female",
        jobs: "Research Associate",
    },
    {
        id: 91,
        name: "Una Fiddeman",
        gender: "Female",
        jobs: "Nuclear Power Engineer",
    },
    {
        id: 92,
        name: "Jarib Casaletto",
        gender: "Male",
        jobs: "Internal Auditor",
    },
    {
        id: 93,
        name: "Zebulon McIlheran",
        gender: "Male",
        jobs: "Senior Developer",
    },
    {
        id: 94,
        name: "Ambrosio Blampied",
        gender: "Male",
        jobs: "Information Systems Manager",
    },
    {
        id: 95,
        name: "Welby Arenson",
        gender: "Male",
        jobs: "Account Representative I",
    },
    {
        id: 96,
        name: "Creight Muzzini",
        gender: "Male",
        jobs: "Sales Associate",
    },
    {
        id: 97,
        name: "Britt Shafe",
        gender: "Female",
        jobs: "Actuary",
    },
    {
        id: 98,
        name: "Brocky Reely",
        gender: "Male",
        jobs: "Staff Accountant III",
    },
    {
        id: 99,
        name: "Doris Weathey",
        gender: "Female",
        jobs: "Administrative Officer",
    },
    {
        id: 100,
        name: "Hilary Crebott",
        gender: "Female",
        jobs: "Biostatistician IV",
    },
];

/** @type {Record<string, any[]>} */
export const dummyDataValues = dummyDataChart.reduce(
    (prev, current, i) => {
        Object.keys(current).forEach((k) => {
            prev[k] = prev[k] || []
            prev[k].push(current[k]);
        });
        return prev;
    },
    {}
);
